language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - "python --version"
  - "pip install -U pip"
  - "pip install -U pytest"
  - "python setup.py install"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install:
  - pip install -r requirements.txt
script: "python setup.py develop && pytest"
