language: python
python:
  - "3.6"
  - "3.7"
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  -  export PYTHONPATH='control/*'
install:
  - pip install -r requirements.txt
script: pytest
